name: agmtrader
services:

  ibkr-gateway:
    container_name: ibkr-gateway
    restart: always
    build:
      context: ../ibkr-gateway/latest
      platforms:
        - "linux/arm64"
      tags:
        - "ib-gateway:latest"
    image: ibkr-gateway:latest
    environment:
      TWS_USERID: ${TWS_USERID}
      TWS_PASSWORD: ${TWS_PASSWORD}
      TRADING_MODE: ${TRADING_MODE:-paper}
      TWS_USERID_PAPER: ${TWS_USERID_PAPER:-}
      TWS_PASSWORD_PAPER: ${TWS_PASSWORD_PAPER:-}
      TWS_SETTINGS_PATH: ${TWS_SETTINGS_PATH:-}
      READ_ONLY_API: ${READ_ONLY_API:-}
      VNC_SERVER_PASSWORD: ${VNC_SERVER_PASSWORD:-}
      TWOFA_TIMEOUT_ACTION: ${TWOFA_TIMEOUT_ACTION:-exit}
      BYPASS_WARNING: ${BYPASS_WARNING:-}
      AUTO_RESTART_TIME: ${AUTO_RESTART_TIME:-}
      AUTO_LOGOFF_TIME: ${AUTO_LOGOFF_TIME:-}
      SAVE_TWS_SETTINGS: ${SAVE_TWS_SETTINGS:-}
      RELOGIN_AFTER_TWOFA_TIMEOUT: ${RELOGIN_AFTER_TWOFA_TIMEOUT:-no}
      TWOFA_EXIT_INTERVAL: ${TWOFA_EXIT_INTERVAL:-60}
      TIME_ZONE: ${TIME_ZONE:-Etc/UTC}
      TZ: ${TIME_ZONE:-Etc/UTC}
      CUSTOM_CONFIG: ${CUSTOM_CONFIG:-NO}
      JAVA_HEAP_SIZE: ${JAVA_HEAP_SIZE:-}
      SSH_TUNNEL: ${SSH_TUNNEL:-}
      SSH_OPTIONS: ${SSH_OPTIONS:-}
      SSH_ALIVE_INTERVAL: ${SSH_ALIVE_INTERVAL:-}
      SSH_ALIVE_COUNT: ${SSH_ALIVE_COUNT:-}
      SSH_PASSPHRASE: ${SSH_PASSPHRASE:-}
      SSH_REMOTE_PORT: ${SSH_REMOTE_PORT:-}
      SSH_USER_TUNNEL: ${SSH_USER_TUNNEL:-}
      SSH_RESTART: ${SSH_RESTART:-}
      SSH_VNC_PORT: ${SSH_VNC_PORT:-}
    networks:
      - singularity-net
    ports:
      - "4001:4003"
      - "4002:4004"
      - "5900:5900"

  ibkr-web-api:
    build: .
    image: ibkr-web-api
    container_name: ibkr-web-api
    environment:
      IBKR_ACCOUNT_ID: "U13313113"
    ports:
      - "5055:5055"
      - "5056:5056"
    volumes:
      - ./webapp:/app/webapp

  agm-trader-socket:
    container_name: agm-trader-socket
    image: agm-trader-socket:latest
    build:
      context: ../agm-trader
      dockerfile: Dockerfile
    env_file:
      - ../agm-trader/.env
    restart: always
    ports:
      - '4444:4444'
    networks:
      - singularity-net
    depends_on:
      - ibkr-gateway

  agm-api:
    container_name: agm-api
    image: agm-api:latest
    build:
      context: ../agm-api
      dockerfile: Dockerfile
    env_file:
      - ../agm-api/.env
    restart: unless-stopped
    volumes:
      - api-db:/app/src/db
      - api-cache:/app/cache
    ports:
      - '5000:5000'
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - agm-net

  agm-hub:
    container_name: agm-hub
    image: agm-hub:latest
    depends_on:
      - agm-api
    build:
      context: ../agm-hub
      dockerfile: Dockerfile
    env_file:
      - ../agm-hub/.env
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - agm-net

volumes:
  api-db:
  api-cache:

networks:
  agm-net:
    driver: bridge