name: agm
services:
  agm-api:
    container_name: agm-api
    image: agm-api:latest
    build:
      context: ../agm-api
      dockerfile: Dockerfile
    env_file:
      - ../agm-api/.env
    restart: unless-stopped
    volumes:
      - api-db:/app/src/db
      - api-cache:/app/cache
    ports:
      - '5000:5000'
    networks:
      - agm-net

  agm-hub:
    container_name: agm-hub
    image: agm-hub:latest
    depends_on:
      - agm-api
    build:
      context: ../agm-hub
      dockerfile: Dockerfile
    env_file:
      - ../agm-hub/.env
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - agm-net

  agm-trader:
    container_name: agm-trader
    image: agm-trader:latest
    build:
      context: ../agm-trader
      dockerfile: Dockerfile
    env_file:
      - ../agm-trader/.env
    restart: always
    ports:
      - '4444:4444'
    volumes:
      - agm-trader-db:/app/src/db
      - agm-trader-cache:/app/cache

volumes:
  agm-trader-db:
  agm-trader-cache:
  api-db:
  api-cache:

networks:
  agm-net:
    driver: bridge