name: ibkr
services:
  ibkr-trading-api:
    build: 
      context: ../ibkr-trading-api
      dockerfile: Dockerfile
    image: ibkr-trading-api
    container_name: ibkr-trading-api
    environment:
      IBKR_ACCOUNT_ID: "U13313113"
    ports:
      - "5055:5055"
      - "5056:5056"
    volumes:
      - ./webapp:/app/webapp
